---
  engines:
    metric:
      exclude_paths:
        - 'src/interfaces/*.d.ts'
        - 'public/manifest.json'
        - 'public/*.js'
        - 'public/*.js.map'
        - 'tsconfig.json'
        - 'src/hooks/useSWR.ts'
        - '.github/**/*.md'
        - '*.md'

  exclude_paths:
    - 'src/interfaces/*.d.ts'
    - 'public/manifest.json'
    - 'public/*.js'
    - 'public/*.js.map'
    - 'tsconfig.json'
    - 'src/hooks/useSWR.ts'
    - '.github/**/*.md'
    - '*.md'
